backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: "site/static/uploads"

collections:
  - name: "sections"
    label: "Sections"
    folder: "site/sections"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
  - name: "projects"
    label: "Projects"
    folder: "site/projects"
    create: false
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
  - name: "goals"
    label: "Goals"
    folder: "site/goals"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
